# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - repository:
      owner: ymtdzzz
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

dockers:
  - image_templates:
      - 'ymtdzzz/otel-tui:{{ .Tag }}-amd64'
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    dockerfile: Dockerfile.goreleaser
  - image_templates:
      - 'ymtdzzz/otel-tui:{{ .Tag }}-arm64'
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64
    dockerfile: Dockerfile.goreleaser

docker_manifests:
- name_template: 'ymtdzzz/otel-tui:{{ .Tag }}'
  image_templates:
  - 'ymtdzzz/otel-tui:{{ .Tag }}-amd64'
  - 'ymtdzzz/otel-tui:{{ .Tag }}-arm64'
  - 'ymtdzzz/otel-tui:latest'
